WS ws://127.0.0.1:8000/ws/rooms/aacebde939c14d8aa33e42942b5b6d1f?token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImE1YTAwNWU5N2NiMWU0MjczMDBlNTJjZGQ1MGYwYjM2Y2Q4MDYyOWIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vaWVtLWxhYnMiLCJhdWQiOiJpZW0tbGFicyIsImF1dGhfdGltZSI6MTc2MDU5MDkxNiwidXNlcl9pZCI6InNWaTc0M2hlRDFUVUhQZFRrT01IQllrRlpKNzMiLCJzdWIiOiJzVmk3NDNoZUQxVFVIUGRUa09NSEJZa0ZaSjczIiwiaWF0IjoxNzYwNTkwOTE2LCJleHAiOjE3NjA1OTQ1MTYsImVtYWlsIjoicGl5dXNoNDAwYW5hbmRAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInBpeXVzaDQwMGFuYW5kQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.gNviFWCszBEezWDq6Vn13fP8NpuhJc2f4OunuiJO8C5TWl15xcpEeBDKz771pMSPjMq7iqwONtm6O6C6xP561sWDPeKpZW4T0N53cKqdB28exmQ82a4gBFkSu2r9-lz4OFndNOiGhCxyMt7C4iSGXhTCP2YYYbI_-ZcLqtix27nnmiGoK7siv8kgs9cKGoiGVd1ZPs_-R_nwqzdtSY7_frkb16_-XQIpHra_zEUttjy75_s-kcisoqUf5kwMYFTARNeCEsZ6uli0KI3pNbTGXCjvdhH-JS6qmHDGKN7_9wZHpLjVSuWceW8DuLU6wzaJYIC6DvveI1LaFW1cOdMtBA
